/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminPagesRouteImport } from './routes/admin/pages'
import { Route as AdminRegistrationsRouteImport } from './routes/admin/registrations'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as GalleryIndexRouteImport } from './routes/gallery/index'
import { Route as GallerySlugRouteImport } from './routes/gallery/$slug'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as PlayersIndexRouteImport } from './routes/players/index'
import { Route as PlayersSlugRouteImport } from './routes/players/$slug'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments/index'
import { Route as TournamentsSlugRouteImport } from './routes/tournaments/$slug'
import { Route as AdminGalleryIndexRouteImport } from './routes/admin/gallery/index'
import { Route as AdminGalleryIdRouteImport } from './routes/admin/gallery/$id'
import { Route as AdminGalleryNewRouteImport } from './routes/admin/gallery/new'
import { Route as AdminNewsIndexRouteImport } from './routes/admin/news/index'
import { Route as AdminNewsIdRouteImport } from './routes/admin/news/$id'
import { Route as AdminNewsNewRouteImport } from './routes/admin/news/new'
import { Route as AdminPlayersIndexRouteImport } from './routes/admin/players/index'
import { Route as AdminPlayersIdRouteImport } from './routes/admin/players/$id'
import { Route as AdminPlayersNewRouteImport } from './routes/admin/players/new'
import { Route as AdminTournamentsIndexRouteImport } from './routes/admin/tournaments/index'
import { Route as AdminTournamentsIdRouteImport } from './routes/admin/tournaments/$id'
import { Route as AdminTournamentsNewRouteImport } from './routes/admin/tournaments/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMediaIdRouteImport } from './routes/api/media/$id'
import { Route as ApiTallyWebhookRouteImport } from './routes/api/tally/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const GallerySlugRoute = GallerySlugRouteImport.update({
  id: '/gallery/$slug',
  path: '/gallery/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersSlugRoute = PlayersSlugRouteImport.update({
  id: '/players/$slug',
  path: '/players/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsSlugRoute = TournamentsSlugRouteImport.update({
  id: '/tournaments/$slug',
  path: '/tournaments/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGalleryIndexRoute = AdminGalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGalleryIdRoute = AdminGalleryIdRouteImport.update({
  id: '/gallery/$id',
  path: '/gallery/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGalleryNewRoute = AdminGalleryNewRouteImport.update({
  id: '/gallery/new',
  path: '/gallery/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNewsIndexRoute = AdminNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNewsIdRoute = AdminNewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNewsNewRoute = AdminNewsNewRouteImport.update({
  id: '/news/new',
  path: '/news/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPlayersIndexRoute = AdminPlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPlayersIdRoute = AdminPlayersIdRouteImport.update({
  id: '/players/$id',
  path: '/players/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPlayersNewRoute = AdminPlayersNewRouteImport.update({
  id: '/players/new',
  path: '/players/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTournamentsIndexRoute = AdminTournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTournamentsIdRoute = AdminTournamentsIdRouteImport.update({
  id: '/tournaments/$id',
  path: '/tournaments/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTournamentsNewRoute = AdminTournamentsNewRouteImport.update({
  id: '/tournaments/new',
  path: '/tournaments/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaIdRoute = ApiMediaIdRouteImport.update({
  id: '/api/media/$id',
  path: '/api/media/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTallyWebhookRoute = ApiTallyWebhookRouteImport.update({
  id: '/api/tally/webhook',
  path: '/api/tally/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/players/$slug': typeof PlayersSlugRoute
  '/tournaments/$slug': typeof TournamentsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/news/': typeof NewsIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/admin/gallery/$id': typeof AdminGalleryIdRoute
  '/admin/gallery/new': typeof AdminGalleryNewRoute
  '/admin/news/$id': typeof AdminNewsIdRoute
  '/admin/news/new': typeof AdminNewsNewRoute
  '/admin/players/$id': typeof AdminPlayersIdRoute
  '/admin/players/new': typeof AdminPlayersNewRoute
  '/admin/tournaments/$id': typeof AdminTournamentsIdRoute
  '/admin/tournaments/new': typeof AdminTournamentsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/tally/webhook': typeof ApiTallyWebhookRoute
  '/admin/gallery/': typeof AdminGalleryIndexRoute
  '/admin/news/': typeof AdminNewsIndexRoute
  '/admin/players/': typeof AdminPlayersIndexRoute
  '/admin/tournaments/': typeof AdminTournamentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/players/$slug': typeof PlayersSlugRoute
  '/tournaments/$slug': typeof TournamentsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/gallery': typeof GalleryIndexRoute
  '/news': typeof NewsIndexRoute
  '/players': typeof PlayersIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/admin/gallery/$id': typeof AdminGalleryIdRoute
  '/admin/gallery/new': typeof AdminGalleryNewRoute
  '/admin/news/$id': typeof AdminNewsIdRoute
  '/admin/news/new': typeof AdminNewsNewRoute
  '/admin/players/$id': typeof AdminPlayersIdRoute
  '/admin/players/new': typeof AdminPlayersNewRoute
  '/admin/tournaments/$id': typeof AdminTournamentsIdRoute
  '/admin/tournaments/new': typeof AdminTournamentsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/tally/webhook': typeof ApiTallyWebhookRoute
  '/admin/gallery': typeof AdminGalleryIndexRoute
  '/admin/news': typeof AdminNewsIndexRoute
  '/admin/players': typeof AdminPlayersIndexRoute
  '/admin/tournaments': typeof AdminTournamentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/players/$slug': typeof PlayersSlugRoute
  '/tournaments/$slug': typeof TournamentsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/news/': typeof NewsIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/admin/gallery/$id': typeof AdminGalleryIdRoute
  '/admin/gallery/new': typeof AdminGalleryNewRoute
  '/admin/news/$id': typeof AdminNewsIdRoute
  '/admin/news/new': typeof AdminNewsNewRoute
  '/admin/players/$id': typeof AdminPlayersIdRoute
  '/admin/players/new': typeof AdminPlayersNewRoute
  '/admin/tournaments/$id': typeof AdminTournamentsIdRoute
  '/admin/tournaments/new': typeof AdminTournamentsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/tally/webhook': typeof ApiTallyWebhookRoute
  '/admin/gallery/': typeof AdminGalleryIndexRoute
  '/admin/news/': typeof AdminNewsIndexRoute
  '/admin/players/': typeof AdminPlayersIndexRoute
  '/admin/tournaments/': typeof AdminTournamentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/account'
    | '/contact'
    | '/login'
    | '/register'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/login'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/registrations'
    | '/admin/settings'
    | '/gallery/$slug'
    | '/news/$slug'
    | '/players/$slug'
    | '/tournaments/$slug'
    | '/admin/'
    | '/gallery/'
    | '/news/'
    | '/players/'
    | '/tournaments/'
    | '/admin/gallery/$id'
    | '/admin/gallery/new'
    | '/admin/news/$id'
    | '/admin/news/new'
    | '/admin/players/$id'
    | '/admin/players/new'
    | '/admin/tournaments/$id'
    | '/admin/tournaments/new'
    | '/api/auth/$'
    | '/api/media/$id'
    | '/api/tally/webhook'
    | '/admin/gallery/'
    | '/admin/news/'
    | '/admin/players/'
    | '/admin/tournaments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/contact'
    | '/login'
    | '/register'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/login'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/registrations'
    | '/admin/settings'
    | '/gallery/$slug'
    | '/news/$slug'
    | '/players/$slug'
    | '/tournaments/$slug'
    | '/admin'
    | '/gallery'
    | '/news'
    | '/players'
    | '/tournaments'
    | '/admin/gallery/$id'
    | '/admin/gallery/new'
    | '/admin/news/$id'
    | '/admin/news/new'
    | '/admin/players/$id'
    | '/admin/players/new'
    | '/admin/tournaments/$id'
    | '/admin/tournaments/new'
    | '/api/auth/$'
    | '/api/media/$id'
    | '/api/tally/webhook'
    | '/admin/gallery'
    | '/admin/news'
    | '/admin/players'
    | '/admin/tournaments'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/account'
    | '/contact'
    | '/login'
    | '/register'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/login'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/registrations'
    | '/admin/settings'
    | '/gallery/$slug'
    | '/news/$slug'
    | '/players/$slug'
    | '/tournaments/$slug'
    | '/admin/'
    | '/gallery/'
    | '/news/'
    | '/players/'
    | '/tournaments/'
    | '/admin/gallery/$id'
    | '/admin/gallery/new'
    | '/admin/news/$id'
    | '/admin/news/new'
    | '/admin/players/$id'
    | '/admin/players/new'
    | '/admin/tournaments/$id'
    | '/admin/tournaments/new'
    | '/api/auth/$'
    | '/api/media/$id'
    | '/api/tally/webhook'
    | '/admin/gallery/'
    | '/admin/news/'
    | '/admin/players/'
    | '/admin/tournaments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GallerySlugRoute: typeof GallerySlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  PlayersSlugRoute: typeof PlayersSlugRoute
  TournamentsSlugRoute: typeof TournamentsSlugRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMediaIdRoute: typeof ApiMediaIdRoute
  ApiTallyWebhookRoute: typeof ApiTallyWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$slug': {
      id: '/gallery/$slug'
      path: '/gallery/$slug'
      fullPath: '/gallery/$slug'
      preLoaderRoute: typeof GallerySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$slug': {
      id: '/players/$slug'
      path: '/players/$slug'
      fullPath: '/players/$slug'
      preLoaderRoute: typeof PlayersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$slug': {
      id: '/tournaments/$slug'
      path: '/tournaments/$slug'
      fullPath: '/tournaments/$slug'
      preLoaderRoute: typeof TournamentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gallery/': {
      id: '/admin/gallery/'
      path: '/gallery'
      fullPath: '/admin/gallery/'
      preLoaderRoute: typeof AdminGalleryIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/gallery/$id': {
      id: '/admin/gallery/$id'
      path: '/gallery/$id'
      fullPath: '/admin/gallery/$id'
      preLoaderRoute: typeof AdminGalleryIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/gallery/new': {
      id: '/admin/gallery/new'
      path: '/gallery/new'
      fullPath: '/admin/gallery/new'
      preLoaderRoute: typeof AdminGalleryNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/news/': {
      id: '/admin/news/'
      path: '/news'
      fullPath: '/admin/news/'
      preLoaderRoute: typeof AdminNewsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/news/$id': {
      id: '/admin/news/$id'
      path: '/news/$id'
      fullPath: '/admin/news/$id'
      preLoaderRoute: typeof AdminNewsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/news/new': {
      id: '/admin/news/new'
      path: '/news/new'
      fullPath: '/admin/news/new'
      preLoaderRoute: typeof AdminNewsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/players/': {
      id: '/admin/players/'
      path: '/players'
      fullPath: '/admin/players/'
      preLoaderRoute: typeof AdminPlayersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/players/$id': {
      id: '/admin/players/$id'
      path: '/players/$id'
      fullPath: '/admin/players/$id'
      preLoaderRoute: typeof AdminPlayersIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/players/new': {
      id: '/admin/players/new'
      path: '/players/new'
      fullPath: '/admin/players/new'
      preLoaderRoute: typeof AdminPlayersNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tournaments/': {
      id: '/admin/tournaments/'
      path: '/tournaments'
      fullPath: '/admin/tournaments/'
      preLoaderRoute: typeof AdminTournamentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tournaments/$id': {
      id: '/admin/tournaments/$id'
      path: '/tournaments/$id'
      fullPath: '/admin/tournaments/$id'
      preLoaderRoute: typeof AdminTournamentsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tournaments/new': {
      id: '/admin/tournaments/new'
      path: '/tournaments/new'
      fullPath: '/admin/tournaments/new'
      preLoaderRoute: typeof AdminTournamentsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$id': {
      id: '/api/media/$id'
      path: '/api/media/$id'
      fullPath: '/api/media/$id'
      preLoaderRoute: typeof ApiMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tally/webhook': {
      id: '/api/tally/webhook'
      path: '/api/tally/webhook'
      fullPath: '/api/tally/webhook'
      preLoaderRoute: typeof ApiTallyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminGalleryIdRoute: typeof AdminGalleryIdRoute
  AdminGalleryNewRoute: typeof AdminGalleryNewRoute
  AdminNewsIdRoute: typeof AdminNewsIdRoute
  AdminNewsNewRoute: typeof AdminNewsNewRoute
  AdminPlayersIdRoute: typeof AdminPlayersIdRoute
  AdminPlayersNewRoute: typeof AdminPlayersNewRoute
  AdminTournamentsIdRoute: typeof AdminTournamentsIdRoute
  AdminTournamentsNewRoute: typeof AdminTournamentsNewRoute
  AdminGalleryIndexRoute: typeof AdminGalleryIndexRoute
  AdminNewsIndexRoute: typeof AdminNewsIndexRoute
  AdminPlayersIndexRoute: typeof AdminPlayersIndexRoute
  AdminTournamentsIndexRoute: typeof AdminTournamentsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminGalleryIdRoute: AdminGalleryIdRoute,
  AdminGalleryNewRoute: AdminGalleryNewRoute,
  AdminNewsIdRoute: AdminNewsIdRoute,
  AdminNewsNewRoute: AdminNewsNewRoute,
  AdminPlayersIdRoute: AdminPlayersIdRoute,
  AdminPlayersNewRoute: AdminPlayersNewRoute,
  AdminTournamentsIdRoute: AdminTournamentsIdRoute,
  AdminTournamentsNewRoute: AdminTournamentsNewRoute,
  AdminGalleryIndexRoute: AdminGalleryIndexRoute,
  AdminNewsIndexRoute: AdminNewsIndexRoute,
  AdminPlayersIndexRoute: AdminPlayersIndexRoute,
  AdminTournamentsIndexRoute: AdminTournamentsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GallerySlugRoute: GallerySlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  PlayersSlugRoute: PlayersSlugRoute,
  TournamentsSlugRoute: TournamentsSlugRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  PlayersIndexRoute: PlayersIndexRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMediaIdRoute: ApiMediaIdRoute,
  ApiTallyWebhookRoute: ApiTallyWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
